### ISSUE TITLE
Positionierung der Karten

### ISSUE THREAD

**Issue by FeuerTeufel94** [ekatioz/cards_against_seriousness#1]
Ich finde die Positionierung der Karten unnötig komplex, lol

**Comment by Fredmaster69** [comment]
sieht aber cool aus 💃

**Comment by ekatioz** [comment]
@FeuerTeufel94 du kannst gerne ein design machen oder so.

Ansonsten lass ich das erst mal so 😅

**Comment by FeuerTeufel94** [comment]
> @FeuerTeufel94 du kannst gerne ein design machen oder so.
> 
> Ansonsten lass ich das erst mal so
Es wäre halt einfacher von der Bedienung her und von der Nutzung des Bildschirms. Und wenn man darüber hovert geht die Karte halt nach oben raus ... Evtl löst das auch das Problem mit dem Erkennen, welche Karte ausgewählt ist. Man könnte die karte dann einfach oben raus gucken lassen, wenn sie ausgewählt ist, oder sogar noch ein stückchen weiter rausschieben ... irgendwie soo :dagger:

**Comment by Fredmaster69** [comment]
Find ich gar nicht schlecht die Idee mit dem rausgucken um zu erkennen dass es ausgewählt ist.

**Comment by ekatioz** [comment]
Aktuell sieht das mit den Karten mehr oder weniger gut aus. Für kleine Displaygrößen (mobile & Portrait) müssen wir uns noch was einfallen lassen.
