### ISSUE TITLE
confirmen mit doppelklick

### ISSUE THREAD

**Issue by Fredmaster69** [ekatioz/cards_against_seriousness#2]
doppelklick makiert bei mir den text. vielleicht sichtbar machen was man confirmed.

**Comment by ekatioz** [comment]
Nach dem Bestätigen soll man nichts mehr machen können, bis man das nächste mal dran ist. Damit ist dann auch klar, dass fertig ist.

Generell ist aber noch nicht so wirklich klar, was man machen wird, um zu bestätigen.

**Comment by ekatioz** [comment]
Wir haben gestern nochmal drüber gequatscht und sind der Meinung das es cool wäre, wenn man die Karte per drag'n'drop auf den Lochtext bestätigen müsste. Dazu soll eine "Dropzone" angezeigt werden, auf der die Karte fallengelassen werden soll.

**Comment by ekatioz** [comment]
Wir lassen das Design erstmal so, deshalb wird das hier unnötig
