### ISSUE TITLE
Auswahlhäufigkeit der Karten 

### ISSUE THREAD

**Issue by Fredmaster69** [ekatioz/cards_against_seriousness#3]
Ein timer oder eine begrenzte Möglichkeit die Karten zu ändern wäre sinnvoll , sonst kann man die Karte noch wechseln wenn der qc die besten auswählt.

**Comment by ekatioz** [comment]
Das ist nur ein Problem, was im aktuellen Zwischenstand besteht. Nachher kannst du nach dem bestätigen deiner Karte nichts mehr ändern.
